### PR TITLE
Relative timestamps for post dates

### PR DESCRIPTION
**Pull request by ghost**
Display relative timestamps for post dates like "Published 33 minutes ago", as well as a tooltip like "February 28 '15 at 8:51".

It uses both the server-side "date" helper to generate them initially and then uses [jquery-timeago](https://github.com/rmm5t/jquery-timeago) to update them on the client-side as time passes (if JS is disabled client-side it'll still display the original date generated on the server but obviously won't update).

### CODE REVIEW

**Comment by haydenbleasel** [comment]
@frenchtouch Awesome! Can I get 2 things before I merge this though:
- Replace `jquery.timeago` with a minified version
- A screenshot of this in action

Cheers :+1:

**Comment by ghost** [comment]
There you go. :)

screenshot from 2015-02-28 15 25 44

There's the screenshot, unfortunately I couldn't take the tooltip as well but its format is `MMMM D [']YY [at] H:mm` which translates to _February 1 '15 at 9:41_ (it's the same format Stack Exchange uses, the only exception being that they don't display the year if it's still the current one, something I don't think is possible without reimplementing Ghost's date helper so I default to always displaying the year).

**Comment by haydenbleasel** [comment]
All good :+1:

**Comment by ghost** [comment]
Cool, have a great day :)

**Comment by haydenbleasel** [comment]
You too!

**Pull request merged**
